### ISSUE TITLE
Override User.find not working on juggler 2.15.0

### ISSUE THREAD

**Issue by lius** [strongloop/loopback-datasource-juggler#427]
I'm using the technique described on http://docs.strongloop.com/display/public/LB/Customizing+models#Customizingmodels-Changetheimplementationofbuilt-inmethods to override User.find method.

To reproduce the error, just generate a new LB application and put the following code in a file inside server/boot/. The error not happens in earlier versions of juggler.

```javascript
module.exports = function (app) {
  var User = app.models.User;
  var find = User.find;

  User.find = function (filter, callback) {
    find.call(User, filter, callback);
  };
};
```

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: undefined is not a function
    at allCb (/Users/lius/development/js/lb/override-builtin-method/node_modules/loopback-datasource-juggler/lib/dao.js:909:7)
    at /Users/lius/development/js/lb/override-builtin-method/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:345:7
    at /Users/lius/development/js/lb/override-builtin-method/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at /Users/lius/development/js/lb/override-builtin-method/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:486:13)
    at process.<anonymous> (/Users/lius/development/js/lb/override-builtin-method/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```

**Comment by bajtos** [comment]
In the current `find` implementation, the argument `filter` is optional. The method checks for argument count. Your implementation does not preserve that number.

```js
// the following call
User.find(cb);
// is translated by your method to
User.find(cb, undefined)
// filter = cb
// callback = undefined
```

Here is the fixed implementation:

```js
  User.find = function (filter, callback) {
    find.apply(User, arguments);
  };
```

**Comment by lius** [comment]
Thank you!
